apiVersion: v1
kind: Service
metadata:
  name: leaseshield-service
  namespace: default
  labels:
    app: leaseshield-ai
spec:
  type: LoadBalancer # 🚀 Instructs OCI to generate an external cloud load balancer asset
  selector:
    app: leaseshield-ai
  ports:
  - protocol: TCP
    port: 80       # 🌐 The public internet port (so you don't have to type :8000 in your browser)
    targetPort: 8000 # The internal container engine port